Refactoring unit tests
FilledStacks/testsweets pull request #10
Opened 2021-06-23 13:34 UTC by ebrahim-soliman

1. Fix all unit tests(except one).
2. Add unit tests to TestSweetsConfigFileService.
3. Refactor testsweets file to reduce boilerplate.
4. Remove duplicate code especially error messages.
5. Change weird makeinstance way of polymorphism to normal and refactor where exists.

2021-06-23 14:30 UTC, FilledStacks requested changes
Great PR. Some minor unit testing issues to make the tests more helpful as documentation.

2021-06-23 14:30 UTC, FilledStacks commented on packages/testsweets/test/test_sweets_config_file_service_test.dart
> +    test(
This test is the same as the one above it

2021-06-23 14:30 UTC, FilledStacks commented on packages/testsweets/test/test_sweets_config_file_service_test.dart
> +      expect(mockFileSystemService.doesFileExist(testDirectoryPath), false);
We can remove this expect. Unit tests mostly only test 1 unit of work at a time

2021-06-23 14:30 UTC, FilledStacks commented on packages/testsweets/test/test_sweets_config_file_service_test.dart
> +    test("get value from map by key", () async {
The test name doesn't say what we're testing. This should be in the format "When given testsweetFileContentMapEntries and ProjectId key should return `3OezzTovG9xFTE5Xw2w1` .

The test case mentioned should be inside a test group called `getStringValueFromMapByKey`. Remember each function gets a `testSuite` / `group` so we don't have to put the name of the function in the test name. The test name is specifically to tell us what parameters are give or what state it is and what we expect the outcome to be.

2021-06-23 14:30 UTC, FilledStacks commented on packages/testsweets/test/test_sweets_config_file_service_test.dart
> +    test("deserialize Config File by key", () async {
Same comment applies here that's written above.

2021-06-23 15:08 UTC, ebrahim-soliman commented
Done

2021-06-25 16:16 UTC, FilledStacks approved these changes

2021-06-25 16:16 UTC, merged